[database]
dsn = "host=localhost port=5432 user=osuproxy password=password dbname=osuproxy sslmode=disable"

[api]
client_id = 1706
client_secret = ""
redirect_uri = "http://localhost/authorize"

[cache]
endpoints = [ "http://localhost:2379" ]

[apiserver]
address = ":8126"
# Note that the reverse proxy config has to be adapted too
allowed_origins = [ "http://localhost", "http://localhost:8000" ]
public_cache = true

# Removing an endpoint will disable it
[[apiserver.endpoint]]
handler = "userinfo"
cache = "never"

[[apiserver.endpoint]]
handler = "osufile"
cache = "always"

[[apiserver.endpoint]]
handler = "scorefile"
cache = "always"

[[apiserver.endpoint]]
handler = "beatmaps_lookup"
cache = "never"

[auth]
address = ":8125"
enable_auth = true

[prom]
address = ":8127"

[application]
api_key_update_url = "http://localhost:8000/?app-apikey="
