[database]
dsn = "osuproxy:password@tcp(db:3306)/osuproxy"

[api]
client_id = 1706
client_secret = ""
redirect_uri = "http://localhost/authorize"

[apiserver]
address = ":8126"
allowed_origins = [ "http://localhost" ]

[[apiserver.endpoint]]
handler = "/api/v1/user/"
cache = "never"

[[apiserver.endpoint]]
handler = "/api/v1/map/"
cache = "always"

[[apiserver.endpoint]]
handler = "/api/v1/score/"
cache = "always"

[auth]
address = ":8125"

[prom]
address = ":8127"