[database]
dsn = "osuproxy:password@tcp(db:3306)/osuproxy"

[api]
client_id = 1706
client_secret = ""
redirect_uri = "http://localhost/authorize"

[apiserver]
address = ":8126"

[[apiserver.endpoint]]
handler = "/api/user/"
cache = "never"

# [[apiserver.endpoint]]
# handler = "test2"
# cache = "always"

[auth]
address = ":8125"