version: "3.2"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: osuproxy
    volumes:
      - ./runtime/db:/var/lib/postgresql/data

  redis:
    image: redis
    restart: always
    volumes:
      - ./runtime/redis:/data
    command: redis-server --appendonly yes

  osu-api-proxy:
    build: "./"
    restart: always
    environment:
      API_CLIENT_SECRET: ${API_CLIENT_SECRET}
    volumes:
      - ./config.toml:/etc/osuproxy/config.toml

  web:
    image: shobble/caddy-cloudflare
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./runtime/caddy_data:/data
    ports:
      - 80:80
      - 443:443
