version: "3.2"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: osuproxy
    volumes:
      - ./runtime/db:/var/lib/postgresql/data

  cache:
    image: gcr.io/etcd-development/etcd:latest
    restart: always
    volumes:
      - ./runtime/cache:/etcd-data
    command: > 
      /usr/local/bin/etcd --data-dir=/etcd-data --name node1
        --initial-advertise-peer-urls http://cache:2380 
        --listen-peer-urls http://0.0.0.0:2380 
        --advertise-client-urls http://cache:2379 
        --listen-client-urls http://0.0.0.0:2379 
        --initial-cluster node1=http://cache:2380

  osu-api-proxy:
    build: "./"
    restart: always
    environment:
      API_CLIENT_SECRET: ${API_CLIENT_SECRET}
    volumes:
      - ./config.toml:/etc/osuproxy/config.toml

  web:
    image: shobble/caddy-cloudflare
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./runtime/caddy_data:/data
    ports:
      - 80:80
      - 443:443
